import type { PromptConfig } from "../types/promptConfig";

export const defaultPromptConfig: PromptConfig = {
  meta: {
    title: "Untitled Image Prompt",
    version: "1.0.0",
    language: "ko",
    createdBy: "prompt-builder",
  },
  brandPositioning: {
    map: {
      xAxis: {
        leftLabel: "Accessible / Trusted / Mainstream",
        rightLabel: "Prestige / Cult / Avant-Garde / Experimental",
        value: 0.5,
      },
      yAxis: {
        bottomLabel: "Utility / Minimal / Refined",
        topLabel: "Lifestyle / Editorial / Statement / Playful",
        value: 0.5,
      },
    },
    selectedKeywords: {
      marketPosition: [],
      brandFunction: [],
      visualExpression: [],
      culturalEdge: [],
    },
    recommendedPresetIds: [],
    recommendedPresetId: null,
    selectedPresetId: null,
    presetSource: "none",
    selectedPoint: {
      x: 0.5,
      y: 0.5,
    },
    styleKeywords: [],
    moodKeywords: [],
    visualKeywords: [],
    paletteHints: [],
    lightingHints: [],
    compositionHints: [],
    negativeHints: [],
    customNotes: "",
    lockPresetToBrand: false,
    summary: {
      positioningSentence: "",
      moodSentence: "",
    },
    manualKeywordOverrides: {
      added: [],
      removed: [],
    },
  },
  brief: {
    purpose: "",
    targetAudience: "",
    platform: "",
    brandTone: "",
    brandContext: "",
  },
  subject: {
    type: "product",
    description: "",
    pose: "",
    expression: "",
    action: "",
    details: [],
  },
  scene: {
    location: "",
    time: "",
    weather: "",
    worldSetting: "",
    backgroundDetails: [],
  },
  style: {
    medium: "photorealistic",
    artDirection: "",
    styleTraits: [],
    rendering: "",
    mood: "",
    texture: "",
    era: "",
  },
  composition: {
    framing: "medium shot",
    angle: "eye level",
    lens: "",
    depthOfField: "",
    subjectPosition: "center",
    negativeSpace: "",
    perspective: "",
  },
  lighting: {
    type: "soft natural lighting",
    direction: "",
    contrast: "medium",
    shadow: "",
    highlight: "",
    mood: "",
  },
  color: {
    palette: [],
    dominantColor: "",
    accentColor: "",
    temperature: "neutral",
    brandColors: [],
    avoidColors: [],
  },
  text: {
    includeText: false,
    content: "",
    language: "none",
    placement: "",
    typography: "",
    legibilityPriority: "medium",
    textOverlayMode: "post-edit",
  },
  constraints: {
    mustInclude: [],
    avoid: ["blurry", "low resolution", "watermark", "random text", "distorted hands", "extra fingers"],
    avoidStyle: [],
    avoidComposition: [],
    brandRestrictions: [],
    safetyRestrictions: [],
  },
  references: {
    imageRefs: [],
    referenceNotes: "",
    lockedElements: [],
  },
  output: {
    aspectRatio: "1:1",
    size: "1024x1024",
    count: 1,
    format: "png",
    quality: "standard",
    transparentBackground: false,
    variationStrength: 0.35,
  },
  modelAdapter: {
    targetModel: "generic",
    promptFormat: "structured-json",
    supportsNegativePrompt: true,
    supportsSeed: false,
    supportsImageReference: false,
  },
};
