import { defaultPromptConfig } from "./default-prompt";
import { summarizeBrandPositioning } from "./positioning-map";
import { deepClone, mergeUniqueStrings } from "./prompt-utils";
import type { PromptConfig, StyleMoodPreset } from "../types/promptConfig";

export const FEATURED_PRESET_IDS = [
  "refined-classic",
  "modern-minimal",
  "expressive-heritage",
  "future-bold",
  "balanced-premium",
] as const;

export const STYLE_MOOD_PRESET_GROUPS = {
  accessibleAndUtility: ["everyday-utility", "trusted-basic", "friendly-lifestyle", "mainstream-pop"],
  modernAndPremium: ["modern-minimal", "balanced-premium", "polished-editorial", "premium-campaign"],
  luxuryAndCraft: ["quiet-luxury", "refined-classic", "atelier-heritage", "collector-editorial"],
  boldAndExperimental: ["pop-statement", "cult-statement", "avant-garde-editorial", "future-bold"],
} as const;

export const styleMoodPresets: StyleMoodPreset[] = [
  {
    id: "everyday-utility",
    name: "Everyday Utility",
    positioningKeywords: ["Accessible", "Utility", "Trusted"],
    mood: "practical, clear, approachable, reliable",
    description: "접근성, 기능성, 신뢰감을 중심으로 한 일상적 브랜드 톤",
    centroid: { x: 0.18, y: 0.18 },
    featured: false,
    group: "accessibleAndUtility",
    promptPatch: {
      brief: { brandTone: "accessible, practical, trusted, everyday" },
      style: {
        artDirection: "clear everyday utility visual direction",
        styleTraits: ["simple clarity", "functional layout", "approachable realism", "low visual friction"],
        mood: "practical, clear, approachable, reliable",
      },
      lighting: { type: "natural soft lighting", contrast: "low", mood: "clear and friendly" },
      color: { palette: ["white", "light gray", "soft blue", "natural green"], temperature: "neutral" },
      composition: { framing: "straightforward centered framing", negativeSpace: "moderate" },
      constraints: { avoid: ["overly luxury styling", "dramatic shadows", "visual clutter"] },
    },
    quadrant: "modern-minimal",
    position: { x: 0.18, y: 0.18 },
    styleKeywords: ["clear everyday utility visual direction", "simple clarity", "functional layout"],
    moodKeywords: ["practical", "clear", "approachable", "reliable"],
    visualKeywords: ["approachable realism", "low visual friction", "straightforward framing"],
    paletteHints: ["white", "light gray", "soft blue", "natural green"],
    lightingHints: ["natural soft lighting", "clear and friendly"],
    compositionHints: ["straightforward centered framing", "moderate negative space"],
    negativeHints: ["overly luxury styling", "dramatic shadows", "visual clutter"],
  },
  {
    id: "trusted-basic",
    name: "Trusted Basic",
    positioningKeywords: ["Accessible", "Trusted", "Utility", "Minimal"],
    mood: "simple, stable, useful, familiar",
    description: "안정적이고 범용적인 기본 브랜드 톤",
    centroid: { x: 0.28, y: 0.28 },
    featured: false,
    group: "accessibleAndUtility",
    promptPatch: {
      brief: { brandTone: "trusted, basic, stable, familiar" },
      style: {
        artDirection: "simple trusted basic brand imagery",
        styleTraits: ["clean information hierarchy", "stable composition", "familiar everyday cues", "minimal decoration"],
        mood: "simple, stable, useful, familiar",
      },
      lighting: { type: "soft even studio lighting", contrast: "low", mood: "stable and reassuring" },
      color: { palette: ["white", "warm gray", "navy", "soft beige"], temperature: "neutral" },
      composition: { framing: "clean centered product or lifestyle framing", negativeSpace: "moderate" },
      constraints: { avoid: ["extreme angles", "experimental styling", "overly decorative elements"] },
    },
    quadrant: "refined-classic",
    position: { x: 0.28, y: 0.28 },
    styleKeywords: ["simple trusted basic brand imagery", "clean information hierarchy", "stable composition"],
    moodKeywords: ["simple", "stable", "useful", "familiar"],
    visualKeywords: ["minimal decoration", "clean centered framing", "everyday cues"],
    paletteHints: ["white", "warm gray", "navy", "soft beige"],
    lightingHints: ["soft even studio lighting", "stable and reassuring"],
    compositionHints: ["clean centered product or lifestyle framing", "moderate negative space"],
    negativeHints: ["extreme angles", "experimental styling", "overly decorative elements"],
  },
  {
    id: "friendly-lifestyle",
    name: "Friendly Lifestyle",
    positioningKeywords: ["Accessible", "Lifestyle", "Playful", "Trusted"],
    mood: "warm, friendly, casual, human",
    description: "친근하고 생활 밀착적인 라이프스타일 감성",
    centroid: { x: 0.25, y: 0.52 },
    featured: false,
    group: "accessibleAndUtility",
    promptPatch: {
      brief: { brandTone: "friendly, lifestyle-driven, accessible, human" },
      style: {
        artDirection: "friendly lifestyle campaign imagery",
        styleTraits: ["human warmth", "casual everyday setting", "soft interaction", "approachable color mood"],
        mood: "warm, friendly, casual, human",
      },
      lighting: { type: "warm natural lifestyle lighting", contrast: "medium", mood: "friendly and relaxed" },
      color: { palette: ["cream", "soft yellow", "warm beige", "muted coral"], temperature: "warm" },
      composition: { framing: "casual lifestyle framing", negativeSpace: "moderate" },
      constraints: { avoid: ["cold sterile lighting", "distant luxury mood", "overly formal composition"] },
    },
    quadrant: "balanced-premium",
    position: { x: 0.25, y: 0.52 },
    styleKeywords: ["friendly lifestyle campaign imagery", "human warmth", "casual everyday setting"],
    moodKeywords: ["warm", "friendly", "casual", "human"],
    visualKeywords: ["soft interaction", "approachable color mood", "casual framing"],
    paletteHints: ["cream", "soft yellow", "warm beige", "muted coral"],
    lightingHints: ["warm natural lifestyle lighting", "friendly and relaxed"],
    compositionHints: ["casual lifestyle framing", "moderate negative space"],
    negativeHints: ["cold sterile lighting", "distant luxury mood", "overly formal composition"],
  },
  {
    id: "mainstream-pop",
    name: "Mainstream Pop",
    positioningKeywords: ["Mainstream Pop", "Campaign", "Playful", "Lifestyle"],
    mood: "bright, popular, energetic, campaign-driven",
    description: "대중적이고 캠페인 친화적인 팝 무드",
    centroid: { x: 0.32, y: 0.75 },
    featured: false,
    group: "accessibleAndUtility",
    promptPatch: {
      brief: { brandTone: "mainstream, playful, campaign-driven, energetic" },
      style: {
        artDirection: "bright mainstream pop campaign direction",
        styleTraits: ["bold approachable color", "campaign-ready layout", "playful visual rhythm", "high recognition"],
        mood: "bright, popular, energetic, campaign-driven",
      },
      lighting: { type: "bright commercial lighting", contrast: "medium", mood: "energetic and optimistic" },
      color: { palette: ["bright white", "pop blue", "sunny yellow", "coral"], temperature: "warm" },
      composition: { framing: "bold campaign framing", negativeSpace: "low to moderate" },
      constraints: { avoid: ["muted luxury-only palette", "overly serious mood", "low-energy composition"] },
    },
    quadrant: "expressive-heritage",
    position: { x: 0.32, y: 0.75 },
    styleKeywords: ["bright mainstream pop campaign direction", "bold approachable color", "campaign-ready layout"],
    moodKeywords: ["bright", "popular", "energetic", "campaign-driven"],
    visualKeywords: ["playful visual rhythm", "high recognition", "bold framing"],
    paletteHints: ["bright white", "pop blue", "sunny yellow", "coral"],
    lightingHints: ["bright commercial lighting", "energetic and optimistic"],
    compositionHints: ["bold campaign framing", "low to moderate negative space"],
    negativeHints: ["muted luxury-only palette", "overly serious mood", "low-energy composition"],
  },
  {
    id: "modern-minimal",
    name: "Modern Minimal",
    positioningKeywords: ["Minimal", "Utility", "Trusted", "Prestige"],
    mood: "clean, modern, calm, structured",
    description: "간결함, 기능성, 모던함, 신뢰감, 세련된 사용성",
    centroid: { x: 0.56, y: 0.2 },
    featured: true,
    group: "modernAndPremium",
    promptPatch: {
      brief: { brandTone: "modern, minimal, functional, trusted" },
      style: {
        artDirection: "modern minimal product/editorial direction",
        styleTraits: ["clean layout", "reduced visual noise", "functional elegance", "precise spacing"],
        mood: "calm, clean, structured, modern",
      },
      lighting: { type: "soft diffused studio lighting", contrast: "low", mood: "clean and controlled" },
      color: { palette: ["white", "light gray", "charcoal", "muted neutral"], temperature: "neutral" },
      composition: { framing: "clean centered or grid-based framing", negativeSpace: "high" },
      constraints: { avoid: ["visual clutter", "excessive decoration", "busy background"] },
    },
    quadrant: "modern-minimal",
    position: { x: 0.56, y: 0.2 },
    styleKeywords: ["modern minimal product/editorial direction", "clean layout", "functional elegance"],
    moodKeywords: ["clean", "modern", "calm", "structured"],
    visualKeywords: ["precise spacing", "grid-based framing", "reduced visual noise"],
    paletteHints: ["white", "light gray", "charcoal", "muted neutral"],
    lightingHints: ["soft diffused studio lighting", "clean and controlled"],
    compositionHints: ["clean centered or grid-based framing", "high negative space"],
    negativeHints: ["visual clutter", "excessive decoration", "busy background"],
  },
  {
    id: "balanced-premium",
    name: "Balanced Premium",
    positioningKeywords: ["Trusted", "Prestige", "Lifestyle", "Minimal", "Editorial"],
    mood: "balanced, polished, premium, versatile",
    description: "너무 튀지 않지만 충분히 고급스러운 기본 프리미엄 톤",
    centroid: { x: 0.6, y: 0.48 },
    featured: true,
    group: "modernAndPremium",
    promptPatch: {
      brief: { brandTone: "balanced, polished, premium, versatile" },
      style: {
        artDirection: "balanced premium lifestyle editorial",
        styleTraits: ["polished composition", "premium but accessible mood", "clean editorial finish", "soft visual hierarchy"],
        mood: "premium, approachable, polished, balanced",
      },
      lighting: { type: "soft premium editorial lighting", contrast: "medium", mood: "polished and approachable" },
      color: { palette: ["soft beige", "charcoal", "cream", "muted navy"], temperature: "neutral" },
      composition: { framing: "clean lifestyle editorial framing", negativeSpace: "moderate" },
      constraints: { avoid: ["extreme experimental styling", "low-quality commercial look", "overly loud color palette"] },
    },
    quadrant: "balanced-premium",
    position: { x: 0.6, y: 0.48 },
    styleKeywords: ["balanced premium lifestyle editorial", "polished composition", "clean editorial finish"],
    moodKeywords: ["balanced", "polished", "premium", "versatile"],
    visualKeywords: ["soft visual hierarchy", "approachable premium", "clean lifestyle framing"],
    paletteHints: ["soft beige", "charcoal", "cream", "muted navy"],
    lightingHints: ["soft premium editorial lighting", "polished and approachable"],
    compositionHints: ["clean lifestyle editorial framing", "moderate negative space"],
    negativeHints: ["extreme experimental styling", "low-quality commercial look", "overly loud color palette"],
  },
  {
    id: "polished-editorial",
    name: "Polished Editorial",
    positioningKeywords: ["Prestige", "Editorial", "Lifestyle", "Minimal"],
    mood: "polished, curated, refined, editorial",
    description: "정돈된 편집 화보 스타일의 프리미엄 무드",
    centroid: { x: 0.65, y: 0.64 },
    featured: false,
    group: "modernAndPremium",
    promptPatch: {
      brief: { brandTone: "polished, editorial, refined, premium" },
      style: {
        artDirection: "polished premium editorial direction",
        styleTraits: ["curated styling", "editorial visual rhythm", "refined details", "premium restraint"],
        mood: "polished, curated, refined, editorial",
      },
      lighting: { type: "soft editorial studio lighting", contrast: "medium", mood: "curated and refined" },
      color: { palette: ["cream", "charcoal", "muted taupe", "deep navy"], temperature: "neutral" },
      composition: { framing: "magazine editorial framing", negativeSpace: "moderate" },
      constraints: { avoid: ["random casual snapshots", "overly playful props", "uncontrolled background"] },
    },
    quadrant: "balanced-premium",
    position: { x: 0.65, y: 0.64 },
    styleKeywords: ["polished premium editorial direction", "curated styling", "editorial visual rhythm"],
    moodKeywords: ["polished", "curated", "refined", "editorial"],
    visualKeywords: ["premium restraint", "refined details", "magazine framing"],
    paletteHints: ["cream", "charcoal", "muted taupe", "deep navy"],
    lightingHints: ["soft editorial studio lighting", "curated and refined"],
    compositionHints: ["magazine editorial framing", "moderate negative space"],
    negativeHints: ["random casual snapshots", "overly playful props", "uncontrolled background"],
  },
  {
    id: "premium-campaign",
    name: "Premium Campaign",
    positioningKeywords: ["Prestige", "Campaign", "Editorial", "Statement"],
    mood: "confident, polished, expressive, premium",
    description: "프리미엄 브랜드 캠페인에 어울리는 선명한 무드",
    centroid: { x: 0.68, y: 0.76 },
    featured: false,
    group: "modernAndPremium",
    promptPatch: {
      brief: { brandTone: "premium, confident, campaign-ready, expressive" },
      style: {
        artDirection: "premium campaign editorial direction",
        styleTraits: ["high-impact brand moment", "polished campaign styling", "confident visual hierarchy", "premium expression"],
        mood: "confident, polished, expressive, premium",
      },
      lighting: { type: "cinematic campaign lighting", contrast: "high", mood: "confident and premium" },
      color: { palette: ["black", "cream", "deep navy", "soft gold"], temperature: "neutral" },
      composition: { framing: "hero campaign framing", negativeSpace: "moderate" },
      constraints: { avoid: ["flat generic studio look", "weak focal point", "overly casual mood"] },
    },
    quadrant: "future-bold",
    position: { x: 0.68, y: 0.76 },
    styleKeywords: ["premium campaign editorial direction", "polished campaign styling", "confident visual hierarchy"],
    moodKeywords: ["confident", "polished", "expressive", "premium"],
    visualKeywords: ["high-impact brand moment", "hero framing", "campaign confidence"],
    paletteHints: ["black", "cream", "deep navy", "soft gold"],
    lightingHints: ["cinematic campaign lighting", "confident and premium"],
    compositionHints: ["hero campaign framing", "moderate negative space"],
    negativeHints: ["flat generic studio look", "weak focal point", "overly casual mood"],
  },
  {
    id: "quiet-luxury",
    name: "Quiet Luxury",
    positioningKeywords: ["Luxury", "Minimal", "Collector", "Prestige"],
    mood: "understated, luxurious, calm, precise",
    description: "조용한 고급감, 절제된 럭셔리, 섬세한 디테일",
    centroid: { x: 0.76, y: 0.22 },
    featured: false,
    group: "luxuryAndCraft",
    promptPatch: {
      brief: { brandTone: "understated, luxurious, precise, premium" },
      style: {
        artDirection: "quiet luxury minimal editorial direction",
        styleTraits: ["understated elegance", "precise material details", "subtle luxury cues", "calm premium restraint"],
        mood: "understated, luxurious, calm, precise",
      },
      lighting: { type: "soft controlled luxury lighting", contrast: "low", mood: "quiet and elevated" },
      color: { palette: ["ivory", "warm gray", "deep brown", "soft black"], temperature: "warm" },
      composition: { framing: "minimal luxury framing", negativeSpace: "high" },
      constraints: { avoid: ["loud logos", "flashy effects", "busy decorative styling"] },
    },
    quadrant: "refined-classic",
    position: { x: 0.76, y: 0.22 },
    styleKeywords: ["quiet luxury minimal editorial direction", "understated elegance", "precise material details"],
    moodKeywords: ["understated", "luxurious", "calm", "precise"],
    visualKeywords: ["subtle luxury cues", "calm premium restraint", "minimal luxury framing"],
    paletteHints: ["ivory", "warm gray", "deep brown", "soft black"],
    lightingHints: ["soft controlled luxury lighting", "quiet and elevated"],
    compositionHints: ["minimal luxury framing", "high negative space"],
    negativeHints: ["loud logos", "flashy effects", "busy decorative styling"],
  },
  {
    id: "refined-classic",
    name: "Refined Classic",
    positioningKeywords: ["Trusted", "Prestige", "Luxury", "Atelier", "Collector"],
    mood: "calm, refined, heritage, premium",
    description: "차분한 프리미엄, 유산, 장인성, 신뢰감, 고급스러운 절제",
    centroid: { x: 0.76, y: 0.35 },
    featured: true,
    group: "luxuryAndCraft",
    promptPatch: {
      brief: { brandTone: "refined, trusted, heritage-inspired, premium" },
      style: {
        artDirection: "refined classic luxury editorial",
        styleTraits: ["heritage-inspired elegance", "crafted details", "subtle premium mood", "timeless composition"],
        mood: "calm, refined, premium, trustworthy",
      },
      lighting: { type: "soft warm cinematic lighting", contrast: "medium", mood: "calm and elegant" },
      color: { palette: ["warm neutral", "deep brown", "ivory", "soft gold"], temperature: "warm" },
      composition: { framing: "balanced editorial framing", negativeSpace: "moderate" },
      constraints: { avoid: ["overly futuristic elements", "loud neon colors", "chaotic composition"] },
    },
    quadrant: "refined-classic",
    position: { x: 0.76, y: 0.35 },
    styleKeywords: ["refined classic luxury editorial", "heritage-inspired elegance", "crafted details"],
    moodKeywords: ["calm", "refined", "heritage", "premium"],
    visualKeywords: ["subtle premium mood", "timeless composition", "balanced editorial framing"],
    paletteHints: ["warm neutral", "deep brown", "ivory", "soft gold"],
    lightingHints: ["soft warm cinematic lighting", "calm and elegant"],
    compositionHints: ["balanced editorial framing", "moderate negative space"],
    negativeHints: ["overly futuristic elements", "loud neon colors", "chaotic composition"],
  },
  {
    id: "atelier-heritage",
    name: "Atelier Heritage",
    positioningKeywords: ["Atelier", "Luxury", "Collector", "Editorial"],
    mood: "crafted, tactile, heritage, artisanal",
    description: "공예적이고 장인적인 헤리티지 무드",
    centroid: { x: 0.82, y: 0.48 },
    featured: false,
    group: "luxuryAndCraft",
    promptPatch: {
      brief: { brandTone: "crafted, artisanal, heritage-driven, premium" },
      style: {
        artDirection: "atelier heritage crafted editorial direction",
        styleTraits: ["tactile material detail", "artisan craftsmanship", "heritage storytelling", "hand-finished mood"],
        mood: "crafted, tactile, heritage, artisanal",
      },
      lighting: { type: "warm directional atelier lighting", contrast: "medium", mood: "crafted and intimate" },
      color: { palette: ["deep brown", "aged brass", "cream", "warm terracotta"], temperature: "warm" },
      composition: { framing: "detail-rich atelier framing", negativeSpace: "moderate" },
      constraints: { avoid: ["sterile tech mood", "plastic-looking textures", "generic commercial background"] },
    },
    quadrant: "expressive-heritage",
    position: { x: 0.82, y: 0.48 },
    styleKeywords: ["atelier heritage crafted editorial direction", "tactile material detail", "artisan craftsmanship"],
    moodKeywords: ["crafted", "tactile", "heritage", "artisanal"],
    visualKeywords: ["heritage storytelling", "hand-finished mood", "detail-rich framing"],
    paletteHints: ["deep brown", "aged brass", "cream", "warm terracotta"],
    lightingHints: ["warm directional atelier lighting", "crafted and intimate"],
    compositionHints: ["detail-rich atelier framing", "moderate negative space"],
    negativeHints: ["sterile tech mood", "plastic-looking textures", "generic commercial background"],
  },
  {
    id: "collector-editorial",
    name: "Collector Editorial",
    positioningKeywords: ["Collector", "Atelier", "Editorial", "Luxury"],
    mood: "collectible, curated, rare, editorial",
    description: "소장 가치와 희소성을 강조하는 고급 에디토리얼 무드",
    centroid: { x: 0.84, y: 0.62 },
    featured: false,
    group: "luxuryAndCraft",
    promptPatch: {
      brief: { brandTone: "collectible, curated, rare, luxury editorial" },
      style: {
        artDirection: "collector-focused luxury editorial direction",
        styleTraits: ["rare object focus", "curated display", "gallery-like composition", "elevated editorial finish"],
        mood: "collectible, curated, rare, editorial",
      },
      lighting: { type: "gallery-like editorial lighting", contrast: "medium", mood: "rare and curated" },
      color: { palette: ["black", "ivory", "antique gold", "deep burgundy"], temperature: "warm" },
      composition: { framing: "curated object-focused editorial framing", negativeSpace: "high" },
      constraints: { avoid: ["mass-market commercial look", "playful casual props", "low-value material feel"] },
    },
    quadrant: "expressive-heritage",
    position: { x: 0.84, y: 0.62 },
    styleKeywords: ["collector-focused luxury editorial direction", "rare object focus", "curated display"],
    moodKeywords: ["collectible", "curated", "rare", "editorial"],
    visualKeywords: ["gallery-like composition", "elevated editorial finish", "object focus"],
    paletteHints: ["black", "ivory", "antique gold", "deep burgundy"],
    lightingHints: ["gallery-like editorial lighting", "rare and curated"],
    compositionHints: ["curated object-focused editorial framing", "high negative space"],
    negativeHints: ["mass-market commercial look", "playful casual props", "low-value material feel"],
  },
  {
    id: "pop-statement",
    name: "Pop Statement",
    positioningKeywords: ["Mainstream Pop", "Campaign", "Playful", "Statement"],
    mood: "bold, popular, expressive, energetic",
    description: "대중적이지만 강한 선언성을 가진 캠페인 무드",
    centroid: { x: 0.42, y: 0.86 },
    featured: false,
    group: "boldAndExperimental",
    promptPatch: {
      brief: { brandTone: "bold, popular, playful, statement-making" },
      style: {
        artDirection: "bold pop statement campaign direction",
        styleTraits: ["high-energy visual impact", "playful statement cues", "bold campaign composition", "popular culture energy"],
        mood: "bold, popular, expressive, energetic",
      },
      lighting: { type: "bright high-energy campaign lighting", contrast: "high", mood: "bold and playful" },
      color: { palette: ["hot pink", "electric blue", "bright yellow", "white"], temperature: "warm" },
      composition: { framing: "dynamic campaign framing", negativeSpace: "low" },
      constraints: { avoid: ["quiet luxury restraint", "muted low-energy palette", "overly formal composition"] },
    },
    quadrant: "future-bold",
    position: { x: 0.42, y: 0.86 },
    styleKeywords: ["bold pop statement campaign direction", "high-energy visual impact", "playful statement cues"],
    moodKeywords: ["bold", "popular", "expressive", "energetic"],
    visualKeywords: ["campaign composition", "popular culture energy", "dynamic framing"],
    paletteHints: ["hot pink", "electric blue", "bright yellow", "white"],
    lightingHints: ["bright high-energy campaign lighting", "bold and playful"],
    compositionHints: ["dynamic campaign framing", "low negative space"],
    negativeHints: ["quiet luxury restraint", "muted low-energy palette", "overly formal composition"],
  },
  {
    id: "cult-statement",
    name: "Cult Statement",
    positioningKeywords: ["Cult", "Statement", "Editorial", "Experimental"],
    mood: "niche, intense, expressive, iconic",
    description: "니치하고 팬덤성이 강한 선언적 브랜드 무드",
    centroid: { x: 0.86, y: 0.78 },
    featured: false,
    group: "boldAndExperimental",
    promptPatch: {
      brief: { brandTone: "cult, statement-driven, intense, niche" },
      style: {
        artDirection: "cult statement editorial direction",
        styleTraits: ["iconic visual tension", "niche cultural edge", "strong silhouette", "expressive statement mood"],
        mood: "niche, intense, expressive, iconic",
      },
      lighting: { type: "dramatic editorial lighting", contrast: "high", mood: "intense and iconic" },
      color: { palette: ["black", "deep red", "dirty white", "chrome"], temperature: "cool" },
      composition: { framing: "strong iconic editorial framing", negativeSpace: "variable" },
      constraints: { avoid: ["safe generic lifestyle mood", "overly soft expression", "mainstream blandness"] },
    },
    quadrant: "future-bold",
    position: { x: 0.86, y: 0.78 },
    styleKeywords: ["cult statement editorial direction", "iconic visual tension", "niche cultural edge"],
    moodKeywords: ["niche", "intense", "expressive", "iconic"],
    visualKeywords: ["strong silhouette", "statement mood", "editorial framing"],
    paletteHints: ["black", "deep red", "dirty white", "chrome"],
    lightingHints: ["dramatic editorial lighting", "intense and iconic"],
    compositionHints: ["strong iconic editorial framing", "variable negative space"],
    negativeHints: ["safe generic lifestyle mood", "overly soft expression", "mainstream blandness"],
  },
  {
    id: "avant-garde-editorial",
    name: "Avant-Garde Editorial",
    positioningKeywords: ["Avant-Garde", "Editorial", "Statement", "Cult"],
    mood: "artistic, unconventional, editorial, sharp",
    description: "전위적이고 감각적인 에디토리얼 무드",
    centroid: { x: 0.92, y: 0.82 },
    featured: false,
    group: "boldAndExperimental",
    promptPatch: {
      brief: { brandTone: "avant-garde, editorial, unconventional, sharp" },
      style: {
        artDirection: "avant-garde editorial visual direction",
        styleTraits: ["unconventional styling", "sharp editorial composition", "artistic visual tension", "unexpected form"],
        mood: "artistic, unconventional, editorial, sharp",
      },
      lighting: { type: "sharp directional editorial lighting", contrast: "high", mood: "artistic and tense" },
      color: { palette: ["black", "white", "chrome silver", "acid green"], temperature: "cool" },
      composition: { framing: "asymmetrical avant-garde framing", negativeSpace: "variable" },
      constraints: { avoid: ["traditional heritage styling", "soft friendly lifestyle mood", "predictable composition"] },
    },
    quadrant: "future-bold",
    position: { x: 0.92, y: 0.82 },
    styleKeywords: ["avant-garde editorial visual direction", "unconventional styling", "sharp editorial composition"],
    moodKeywords: ["artistic", "unconventional", "editorial", "sharp"],
    visualKeywords: ["artistic visual tension", "unexpected form", "asymmetrical framing"],
    paletteHints: ["black", "white", "chrome silver", "acid green"],
    lightingHints: ["sharp directional editorial lighting", "artistic and tense"],
    compositionHints: ["asymmetrical avant-garde framing", "variable negative space"],
    negativeHints: ["traditional heritage styling", "soft friendly lifestyle mood", "predictable composition"],
  },
  {
    id: "future-bold",
    name: "Future Bold",
    positioningKeywords: ["Cult", "Avant-Garde", "Experimental", "Statement"],
    mood: "bold, futuristic, disruptive, high-impact",
    description: "실험적, 전위적, 강한 시각 충격, 니치하거나 컬트적인 이미지",
    centroid: { x: 0.94, y: 0.9 },
    featured: true,
    group: "boldAndExperimental",
    promptPatch: {
      brief: { brandTone: "bold, experimental, futuristic, disruptive" },
      style: {
        artDirection: "future-facing avant-garde visual direction",
        styleTraits: ["unconventional composition", "sharp contrast", "experimental form", "high-impact visual tension"],
        mood: "bold, futuristic, disruptive, intense",
      },
      lighting: { type: "dramatic high-contrast lighting", contrast: "high", mood: "intense and futuristic" },
      color: { palette: ["black", "electric blue", "chrome silver", "acid green"], temperature: "cool" },
      composition: { framing: "dynamic asymmetrical framing", negativeSpace: "variable" },
      constraints: { avoid: ["safe generic composition", "soft lifestyle mood", "traditional heritage styling"] },
    },
    quadrant: "future-bold",
    position: { x: 0.94, y: 0.9 },
    styleKeywords: ["future-facing avant-garde visual direction", "unconventional composition", "high-impact visual tension"],
    moodKeywords: ["bold", "futuristic", "disruptive", "high-impact"],
    visualKeywords: ["experimental form", "sharp contrast", "dynamic framing"],
    paletteHints: ["black", "electric blue", "chrome silver", "acid green"],
    lightingHints: ["dramatic high-contrast lighting", "intense and futuristic"],
    compositionHints: ["dynamic asymmetrical framing", "variable negative space"],
    negativeHints: ["safe generic composition", "soft lifestyle mood", "traditional heritage styling"],
  },
  {
    id: "expressive-heritage",
    name: "Expressive Heritage",
    positioningKeywords: ["Atelier", "Campaign", "Lifestyle", "Editorial", "Statement"],
    mood: "rich, crafted, expressive, cultural",
    description: "전통을 기반으로 하지만 표현력이 강한 브랜드, 캠페인성, 스토리텔링",
    centroid: { x: 0.65, y: 0.65 },
    featured: true,
    group: "luxuryAndCraft",
    promptPatch: {
      brief: { brandTone: "crafted, expressive, cultural, story-driven" },
      style: {
        artDirection: "expressive heritage editorial campaign",
        styleTraits: ["rich texture", "crafted visual details", "editorial storytelling", "heritage with expressive energy"],
        mood: "rich, warm, cultural, expressive",
      },
      lighting: { type: "warm cinematic directional lighting", contrast: "medium", mood: "story-driven and atmospheric" },
      color: { palette: ["deep red", "warm brown", "cream", "muted gold"], temperature: "warm" },
      composition: { framing: "editorial storytelling composition", negativeSpace: "moderate" },
      constraints: { avoid: ["flat generic studio look", "cold sterile lighting", "overly minimal composition"] },
    },
    quadrant: "expressive-heritage",
    position: { x: 0.65, y: 0.65 },
    styleKeywords: ["expressive heritage editorial campaign", "rich texture", "crafted visual details"],
    moodKeywords: ["rich", "crafted", "expressive", "cultural"],
    visualKeywords: ["editorial storytelling", "heritage energy", "story composition"],
    paletteHints: ["deep red", "warm brown", "cream", "muted gold"],
    lightingHints: ["warm cinematic directional lighting", "story-driven and atmospheric"],
    compositionHints: ["editorial storytelling composition", "moderate negative space"],
    negativeHints: ["flat generic studio look", "cold sterile lighting", "overly minimal composition"],
  },
];

export const getStyleMoodPresetById = (id: string) => styleMoodPresets.find((preset) => preset.id === id);

export const getFeaturedStyleMoodPresets = () => styleMoodPresets.filter((preset) => preset.featured);

const mergePatch = (config: PromptConfig, preset: StyleMoodPreset) => {
  const next = deepClone(config);
  const patch = preset.promptPatch;

  next.brief.brandTone = next.brief.brandTone.trim() ? next.brief.brandTone : patch.brief?.brandTone ?? next.brief.brandTone;
  next.style.artDirection = next.style.artDirection.trim()
    ? next.style.artDirection
    : patch.style?.artDirection ?? next.style.artDirection;
  next.style.mood = next.style.mood.trim() ? next.style.mood : patch.style?.mood ?? next.style.mood;
  next.style.styleTraits = mergeUniqueStrings(next.style.styleTraits, patch.style?.styleTraits);

  if (!next.color.brandColors?.length) {
    next.color.palette = mergeUniqueStrings(next.color.palette, patch.color?.palette).slice(0, 8);
  }
  next.color.temperature = next.color.temperature ?? patch.color?.temperature;
  next.constraints.avoid = mergeUniqueStrings(next.constraints.avoid, patch.constraints?.avoid);

  next.lighting = {
    ...next.lighting,
    type:
      !next.lighting.type.trim() || next.lighting.type === defaultPromptConfig.lighting.type
        ? patch.lighting?.type ?? next.lighting.type
        : next.lighting.type,
    contrast: next.lighting.contrast ?? patch.lighting?.contrast,
    mood: next.lighting.mood?.trim() ? next.lighting.mood : patch.lighting?.mood ?? next.lighting.mood,
  };

  next.composition = {
    ...next.composition,
    framing:
      !next.composition.framing.trim() || next.composition.framing === defaultPromptConfig.composition.framing
        ? patch.composition?.framing ?? next.composition.framing
        : next.composition.framing,
    negativeSpace: next.composition.negativeSpace?.trim()
      ? next.composition.negativeSpace
      : patch.composition?.negativeSpace ?? next.composition.negativeSpace,
  };

  return next;
};

export const applyStyleMoodPreset = (config: PromptConfig, presetId: string): PromptConfig => {
  const preset = getStyleMoodPresetById(presetId);
  if (!preset) return config;

  const next = mergePatch(config, preset);
  const summary = summarizeBrandPositioning({
    selectedKeywords: preset.positioningKeywords,
    preset,
  });

  next.brandPositioning = {
    ...next.brandPositioning,
    recommendedPresetIds: next.brandPositioning.recommendedPresetIds.length
      ? next.brandPositioning.recommendedPresetIds
      : [preset.id],
    recommendedPresetId: next.brandPositioning.recommendedPresetId ?? preset.id,
    selectedPresetId: preset.id,
    presetSource: next.brandPositioning.presetSource === "none" ? "recommended" : next.brandPositioning.presetSource,
    selectedQuadrant: preset.quadrant,
    selectedPoint: preset.centroid,
    appliedPresetName: preset.name,
    styleKeywords: [...preset.styleKeywords],
    moodKeywords: [...preset.moodKeywords],
    visualKeywords: [...preset.visualKeywords],
    paletteHints: [...preset.paletteHints],
    lightingHints: [...preset.lightingHints],
    compositionHints: [...preset.compositionHints],
    negativeHints: [...preset.negativeHints],
    summary,
  };

  return next;
};
